// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuo1jNA9-jHnxf_88IROA1MvCvX3ZsRM8',
    appId: '1:44078977039:web:ba114c6bfdc52b6f2c137a',
    messagingSenderId: '44078977039',
    projectId: 'catastrophic-risk-analytics',
    authDomain: 'catastrophic-risk-analytics.firebaseapp.com',
    storageBucket: 'catastrophic-risk-analytics.appspot.com',
    measurementId: 'G-TC6J3V0EJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIR6qcSPXtEovaXPsmDaog_UbYuBYffz4',
    appId: '1:44078977039:android:a18de5125b3b3c982c137a',
    messagingSenderId: '44078977039',
    projectId: 'catastrophic-risk-analytics',
    storageBucket: 'catastrophic-risk-analytics.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXgIyYfnFrMW5VZgHMgO1TXNRr8fRdZrA',
    appId: '1:44078977039:ios:cd9164b2929994582c137a',
    messagingSenderId: '44078977039',
    projectId: 'catastrophic-risk-analytics',
    storageBucket: 'catastrophic-risk-analytics.appspot.com',
    iosClientId: '44078977039-t7dpd79jntrv6d8cmq5mejl0o711579s.apps.googleusercontent.com',
    iosBundleId: 'in.catastrophe.vizualize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXgIyYfnFrMW5VZgHMgO1TXNRr8fRdZrA',
    appId: '1:44078977039:ios:03992871f58a30b62c137a',
    messagingSenderId: '44078977039',
    projectId: 'catastrophic-risk-analytics',
    storageBucket: 'catastrophic-risk-analytics.appspot.com',
    iosClientId: '44078977039-v593og0mivtmm7a045fdi3nqfkjusugv.apps.googleusercontent.com',
    iosBundleId: 'in.catastrophe.vizualize.RunnerTests',
  );
}
